name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: day 5 validation
      id: day-5-validation
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DAY-5-VALIDATION_RESULTS: "${{steps.day-5-validation.outputs.result}}"
      with:
        runners: day-5-validation
